
import { IndustryData } from './types';

const createEntry = (id: string, name: string, owner: string, kab: 'Pacitan' | 'Ponorogo', kec: string, skala: 'Kecil' | 'Menengah' | 'Besar', compliance?: any): IndustryData => ({
  id,
  badanUsaha: name.startsWith('PT') ? 'PT' : name.startsWith('CV') ? 'CV' : 'UD',
  namaPerusahaan: name,
  jenisIjin: 'PBPHH',
  userIdRPBBI: compliance?.userId || 'P' + (1000 + parseInt(id)),
  namaPemilik: owner,
  kabupaten: kab,
  kecamatan: kec,
  alamatPabrik: `Kecamatan ${kec}, Kabupaten ${kab}`,
  perijinan: {
    noPBPHH: 'SK.' + id + '/Menlhk/Setjen/2023',
    tanggal: '2023-01-01',
    noNIB: '912000' + id.padStart(4, '0'),
  },
  mesin: {
    kapasitas: skala === 'Besar' ? 70000 : skala === 'Menengah' ? 5000 : 1500,
    skala: skala,
    jenisMesin: 'Bandsaw 36"',
    jumlah: skala === 'Besar' ? 3 : 1,
    modalUsaha: skala === 'Besar' ? 500000000 : skala === 'Menengah' ? 150000000 : 50000000,
  },
  bahanBaku: 'Hutan Rakyat',
  compliance: compliance?.status || {
    tenagaTeknis: 'Sudah',
    hakAksesRPBBI: 'Belum',
    rkophh: 'Sudah',
    dokumenAngkut: 'Sudah',
  },
  kondisiSaatIni: 'Aktif',
  kendala: '-',
  pembinaan: '-',
  tanggalPembinaan: '',
  riwayatPembinaan: [],
});

export const INITIAL_DATA: IndustryData[] = [
  // --- PACITAN (65 Records) ---
  createEntry('1', 'PT Linggarjati Mahardika Mulia 2', 'Junaedi Wasisto N', 'Pacitan', 'Pacitan', 'Besar', { userId: 'P8639' }),
  createEntry('2', 'PT Putra Tunas Subur', 'Hari Wahyono', 'Pacitan', 'Arjosari', 'Besar', { userId: 'P5528' }),
  createEntry('3', 'PT Linggarjati Mahardika Mulia', 'Effendi Bhudi Wirwan', 'Pacitan', 'Kebonagung', 'Besar', { userId: 'P5629' }),
  createEntry('4', 'UD Tunas Subur', 'Hari Wahyono', 'Pacitan', 'Tulakan', 'Besar', { userId: 'P5528' }),
  createEntry('5', 'PT Alam Guna Jaya Sejahtera', 'Ali Djoko Sugianto', 'Pacitan', 'Punung', 'Besar', { userId: 'P8173' }),
  createEntry('6', 'PT Tunas Oetama Pacitan', 'I Putu Arta Nadi', 'Pacitan', 'Donorojo', 'Menengah', { userId: 'P6772' }),
  createEntry('7', 'UD Inti Buana', 'Ahmad Hariadi', 'Pacitan', 'Tulakan', 'Menengah', { userId: 'P7865' }),
  createEntry('8', 'UD Enggal Dadi 2', 'Supriyadi', 'Pacitan', 'Tulakan', 'Menengah', { userId: 'P8643' }),
  createEntry('9', 'UD Arga Putra', 'Maridi', 'Pacitan', 'Nawangan', 'Menengah', { userId: 'P8642' }),
  createEntry('10', 'UD Sumber Rejeki', 'Giyanto', 'Pacitan', 'Tegalombo', 'Menengah', { userId: 'P7044' }),
  createEntry('11', 'UD Temon Raya', 'Son Haji', 'Pacitan', 'Arjosari', 'Menengah', { userId: 'P7922' }),
  createEntry('12', 'UD Ayem Tentrem', 'No. Name', 'Pacitan', 'Ngadirojo', 'Menengah', { userId: 'P7862' }),
  createEntry('13', 'UD Sido Makmur (Ngadirojo)', 'M. Januari Muin', 'Pacitan', 'Ngadirojo', 'Menengah', { userId: 'P9311' }),
  createEntry('14', 'UD Bintang Surya Perkasa', 'Mesiran', 'Pacitan', 'Punung', 'Menengah', { userId: '000' }),
  createEntry('15', 'UD Anugrah Jaya', 'Ahmad Sadikin', 'Pacitan', 'Tulakan', 'Menengah', { userId: '000' }),
  createEntry('16', 'UD Anugerah Mandiri', 'Yono Hatmoko', 'Pacitan', 'Kebonagung', 'Kecil', { userId: '000' }),
  createEntry('17', 'UD Jaya Abadi', 'Sugito', 'Pacitan', 'Nawangan', 'Kecil', { userId: '000' }),
  createEntry('18', 'UD Sarwo Asih Sentosa', 'Saryadi', 'Pacitan', 'Bandar', 'Kecil', { userId: '000' }),
  createEntry('19', 'UD Mekar Dadi', 'Ajar Suseto', 'Pacitan', 'Tulakan', 'Kecil', { userId: 'P8639' }),
  createEntry('20', 'UD Lembah Subur', 'Suparno', 'Pacitan', 'Tulakan', 'Kecil', { userId: 'P8641' }),
  createEntry('21', 'UD Enggal Dadi', 'Sutrisno', 'Pacitan', 'Tulakan', 'Kecil', { userId: 'P9182' }),
  createEntry('22', 'UD Sami Makmur', 'Lukman Hakim', 'Pacitan', 'Punung', 'Kecil', { userId: 'P9152' }),
  createEntry('23', 'UD Bangun Jaya Sejahtera', 'Berta Septiana', 'Pacitan', 'Tulakan', 'Kecil', { userId: 'P9411' }),
  createEntry('24', 'UD Bina Mandiri', 'Nur Arifin', 'Pacitan', 'Tegalombo', 'Kecil', { userId: '000' }),
  createEntry('25', 'UD Rahayu', 'Widodo', 'Pacitan', 'Nawangan', 'Kecil', { userId: 'P9197' }),
  createEntry('26', 'UD Kurnia Jaya', 'Edy Mulyono', 'Pacitan', 'Sudimoro', 'Kecil', { userId: '000' }),
  createEntry('27', 'UD Empat Lima', 'Setyo Wahono', 'Pacitan', 'Tulakan', 'Kecil', { userId: 'P9025' }),
  createEntry('28', 'UD Parnyoto Wood Industries', 'Parnyoto', 'Pacitan', 'Tulakan', 'Kecil', { userId: 'P9183' }),
  createEntry('29', 'UD Sido Makmur', 'Muhammad Januar Muin', 'Pacitan', 'Pacitan', 'Kecil', { userId: 'P7859' }),
  createEntry('30', 'UD Dua Putri', 'Imam Sucipto', 'Pacitan', 'Bandar', 'Kecil', { userId: 'P9149' }),
  createEntry('31', 'UD Tofa Oetama Sejahtera', 'Imam Mustofa', 'Pacitan', 'Kebonagung', 'Kecil', { userId: 'P9151' }),
  createEntry('32', 'UD Kembar Agung Group', 'Agung Sagiri', 'Pacitan', 'Tulakan', 'Kecil', { userId: 'P9412' }),
  createEntry('33', 'UD Mitra Harmoni', 'Triawan', 'Pacitan', 'Pacitan', 'Kecil', { userId: 'P9138' }),
  createEntry('34', 'UD Rimba Lestari', 'Rismawati', 'Pacitan', 'Punung', 'Kecil', { userId: '000' }),
  createEntry('35', 'UD Surya Cipta Gemilang', 'Imam Mafakir Al Alim', 'Pacitan', 'Punung', 'Kecil', { userId: 'P9136' }),
  createEntry('36', 'UD Ronggo Jati', 'Abdul Roni', 'Pacitan', 'Punung', 'Kecil', { userId: '000' }),
  createEntry('37', 'UD Anugrah Abadi', 'Wawan Budi Wasono', 'Pacitan', 'Nawangan', 'Kecil', { userId: 'P9137' }),
  createEntry('38', 'UD Rojas Mandiri', 'Nihayatur Rosidah', 'Pacitan', 'Bandar', 'Kecil', { userId: 'P9150' }),
  createEntry('39', 'UD Angelita', 'Sargianto', 'Pacitan', 'Bandar', 'Kecil', { userId: 'P9196' }),
  createEntry('40', 'UD Tekad Sejati', 'Puji Astuti', 'Pacitan', 'Pringkuku', 'Kecil', { userId: '000' }),
  createEntry('41', 'UD Putra Albasia Mandiri', 'Agus Soleha Putra', 'Pacitan', 'Pacitan', 'Kecil', { userId: '000' }),
  createEntry('42', 'UD Larasati', 'Larasati', 'Pacitan', 'Kebonagung', 'Kecil', { userId: 'P9163' }),
  createEntry('43', 'UD Mekar Dadi Adiguna', 'Heru Purnomo', 'Pacitan', 'Tulakan', 'Kecil', { userId: 'P9422' }),
  createEntry('44', 'UD Banjaran Sejahtera', 'Anjasmara Wirabakti', 'Pacitan', 'Nawangan', 'Kecil', { userId: 'P9304' }),
  createEntry('45', 'UD Sumber Makmur', 'Tumadi', 'Pacitan', 'Tegalombo', 'Kecil', { userId: '000' }),
  createEntry('46', 'UD Wiji Lestari', 'Susanto', 'Pacitan', 'Nawangan', 'Kecil', { userId: 'P9425' }),
  createEntry('47', 'UD Karya Manunggal', 'Imam Sayuti', 'Pacitan', 'Pacitan', 'Kecil', { userId: '000' }),
  createEntry('48', 'UD Mugo Barokah', 'Arif Santoso', 'Pacitan', 'Tegalombo', 'Kecil', { userId: '000' }),
  createEntry('49', 'UD Rizky Sejati', 'Setyo Widodo', 'Pacitan', 'Pacitan', 'Kecil', { userId: '000' }),
  createEntry('50', 'UD Atmajaya', 'Ganang Satriya Atmaja', 'Pacitan', 'Punung', 'Kecil', { userId: '000' }),
  createEntry('51', 'UD Sami Jaya', 'Samino', 'Pacitan', 'Nawangan', 'Kecil', { userId: '000' }),
  createEntry('52', 'UD Sono Manunggal', 'Danang Purwandito', 'Pacitan', 'Arjosari', 'Kecil', { userId: 'P9312' }),
  createEntry('53', 'UD Hasil Karya', 'Dhimas Arbiansyah', 'Pacitan', 'Tulakan', 'Kecil', { userId: '000' }),
  createEntry('54', 'UD Setya Mulya', 'Purwandi', 'Pacitan', 'Kebonagung', 'Kecil', { userId: '000' }),
  createEntry('55', 'UD Berkah Dadi Mulyo', 'Sumarji', 'Pacitan', 'Sudimoro', 'Kecil', { userId: '000' }),
  createEntry('56', 'UD Lancar Jaya', 'Hadi Wiyono', 'Pacitan', 'Kebonagung', 'Kecil', { userId: '000' }),
  createEntry('57', 'UD Sumber Urip', 'Miskat', 'Pacitan', 'Tegalombo', 'Kecil', { userId: '000' }),
  createEntry('58', 'UD Murai Bergema', 'Muhammad Rizal', 'Pacitan', 'Arjosari', 'Kecil', { userId: '000' }),
  createEntry('59', 'UD Barokah Sengon', 'Teguh Setiawan', 'Pacitan', 'Punung', 'Kecil', { userId: '000' }),
  createEntry('60', 'UD Karya Mandiri', 'Agus Wahyono', 'Pacitan', 'Tulakan', 'Kecil', { userId: '000' }),
  createEntry('61', 'UD Putra Enggal Dadi', 'Tulaji', 'Pacitan', 'Tulakan', 'Kecil', { userId: '000' }),
  createEntry('62', 'UD Giri Pace Succesindo', 'Hadi Supangat', 'Pacitan', 'Donorojo', 'Kecil', { userId: '000' }),
  createEntry('63', 'UD Hidup Baru Pacitan', 'Yudi Timur', 'Pacitan', 'Punung', 'Kecil', { userId: '000' }),
  createEntry('64', 'UD Sukmastik', 'Sukatman', 'Pacitan', 'Punung', 'Kecil', { userId: '000' }),
  createEntry('65', 'UD Kiya Putra', 'Tutik Trisnawati', 'Pacitan', 'Ngadirojo', 'Kecil', { userId: '000' }),

  // --- PONOROGO (37 Records) ---
  createEntry('66', 'CV Pinus Jaya', 'Waris Susanto', 'Ponorogo', 'Ponorogo', 'Besar', { userId: '000' }),
  createEntry('67', 'UD Wahyu Jaya Abadi', 'Ari Nugroho', 'Ponorogo', 'Jenangan', 'Menengah', { userId: 'P5527' }),
  createEntry('68', 'UD Mulia', 'Jumangin', 'Ponorogo', 'Babadan', 'Menengah', { userId: 'P8621' }),
  createEntry('69', 'UD Jati Mulya', 'Slamet Widodo', 'Ponorogo', 'Slahung', 'Menengah', { userId: 'P8619' }),
  createEntry('70', 'UD Sumber Rejeki', 'Jaimin', 'Ponorogo', 'Ngrayun', 'Menengah', { userId: '000' }),
  createEntry('71', 'UD Jati Indah', 'Suryadi', 'Ponorogo', 'Pulung', 'Menengah', { userId: 'P7457' }),
  createEntry('72', 'UD Sri Mulya Utama', 'Juri', 'Ponorogo', 'Ngebel', 'Menengah', { userId: 'P7799' }),
  createEntry('73', 'UD Mulyo Rahayu', 'Mulyono', 'Ponorogo', 'Slahung', 'Menengah', { userId: 'P9053' }),
  createEntry('74', 'UD Jati Rifqi', 'Hadi Iskandar', 'Ponorogo', 'Jenangan', 'Kecil', { userId: '000' }),
  createEntry('75', 'UD Sari Jaya Mulya', 'Kamari', 'Ponorogo', 'Ngebel', 'Kecil', { userId: '000' }),
  createEntry('76', 'UD Jati Mulya', 'Mubasyir', 'Ponorogo', 'Babadan', 'Kecil', { userId: '000' }),
  createEntry('77', 'UD Jati Intan', 'Sujiono', 'Ponorogo', 'Jenangan', 'Kecil', { userId: '000' }),
  createEntry('78', 'UD Karya Mandiri', 'Sumardi', 'Ponorogo', 'Sawoo', 'Kecil', { userId: '000' }),
  createEntry('79', 'UD Sulur Jati', 'Sapuwan', 'Ponorogo', 'Jenangan', 'Kecil', { userId: '000' }),
  createEntry('80', 'UD Sengon Mandiri', 'M. Ali Sudarsono', 'Ponorogo', 'Slahung', 'Kecil', { userId: '000' }),
  createEntry('81', 'UD Indiya Jaya', 'Danang Yulianto', 'Ponorogo', 'Ngrayun', 'Kecil', { userId: '000' }),
  createEntry('82', 'UD Jati Luhur', 'Parkun', 'Ponorogo', 'Jenangan', 'Kecil', { userId: '000' }),
  createEntry('83', 'UD Berkah Bersama', 'Alfi Arifin', 'Ponorogo', 'Slahung', 'Kecil', { userId: 'P9424' }),
  createEntry('84', 'UD Berkah Cahaya', 'Sugianto', 'Ponorogo', 'Ngrayun', 'Kecil', { userId: '000' }),
  createEntry('85', 'UD Jati Makmur', 'Mujito', 'Ponorogo', 'Sawoo', 'Kecil', { userId: '000' }),
  createEntry('86', 'UD Berlian Jati', 'Agus Tri Hartono', 'Ponorogo', 'Babadan', 'Kecil', { userId: '000' }),
  createEntry('87', 'UD Jati Maju', 'Pemilik Jati Maju', 'Ponorogo', 'Babadan', 'Kecil', { userId: '000' }),
  createEntry('88', 'UD Bagus Widodo Lestari', 'Meseni', 'Ponorogo', 'Jenangan', 'Kecil', { userId: '000' }),
  createEntry('89', 'UD Jati Intan', 'Sujiono', 'Ponorogo', 'Jenangan', 'Kecil', { userId: '000' }),
  createEntry('90', 'UD Sumber Sari', 'Suhadi', 'Ponorogo', 'Jenangan', 'Kecil', { userId: '000' }),
  createEntry('91', 'UD Jati Diri', 'Fathan', 'Ponorogo', 'Siman', 'Kecil', { userId: '000' }),
  createEntry('92', 'UD Karunia Makmur', 'Pajar Susanto', 'Ponorogo', 'Bungkal', 'Kecil', { userId: '000' }),
  createEntry('93', 'UD Muda Abadi Group', 'Yani Guntoko', 'Ponorogo', 'Slahung', 'Kecil', { userId: '000' }),
  createEntry('94', 'UD Barokah Mebel', 'Ahmad Saifudin', 'Ponorogo', 'Balong', 'Kecil', { userId: '000' }),
  createEntry('95', 'UD Dhimas', 'Eny Kurniasari', 'Ponorogo', 'Slahung', 'Kecil', { userId: '000' }),
  createEntry('96', 'UD Rayyan Furniture', 'Dedi Mukti Prasetyo', 'Ponorogo', 'Siman', 'Kecil', { userId: 'P9402' }),
  createEntry('97', 'UD Ariza Jaya', 'Ariza Jaya Saputra', 'Ponorogo', 'Slahung', 'Kecil', { userId: '000' }),
  createEntry('98', 'UD Ridho', 'Supriyadi', 'Ponorogo', 'Ponorogo', 'Kecil', { userId: '000' }),
  createEntry('99', 'UD Ika Putri', 'Eva Sukidi', 'Ponorogo', 'Ngrayun', 'Kecil', { userId: '000' }),
  createEntry('100', 'UD Puncak Jaya', 'Risdianto', 'Ponorogo', 'Pulung', 'Kecil', { userId: '000' }),
  createEntry('101', 'UD Kari', 'Sukari', 'Ponorogo', 'Ponorogo', 'Kecil', { userId: '000' }),
  createEntry('102', 'UD Rizky Barokah', 'Rizky Dwi Wardana', 'Ponorogo', 'Sambit', 'Kecil', { userId: '000' }),
];
